import { Shield, CheckCircle, XCircle, Clock, AlertTriangle, Download, Award } from 'lucide-react';
import { ComplianceCheck, Loan } from '../types';

interface ComplianceViewProps {
  checks: ComplianceCheck[];
  loans: Loan[];
}

const statusConfig = {
  Passed: { icon: CheckCircle, color: 'text-green-600', bg: 'bg-green-100' },
  Failed: { icon: XCircle, color: 'text-red-600', bg: 'bg-red-100' },
  Pending: { icon: Clock, color: 'text-amber-600', bg: 'bg-amber-100' },
};

export default function ComplianceView({ checks, loans }: ComplianceViewProps) {
  const passedCount = checks.filter(c => c.status === 'Passed').length;
  const failedCount = checks.filter(c => c.status === 'Failed').length;
  const pendingCount = checks.filter(c => c.status === 'Pending').length;

  const highRiskLoans = loans.filter(l => l.defaultProbability > 5);
  const compliantLoans = loans.filter(l => l.defaultProbability <= 5);

  const generateCertificate = (loan: Loan) => {
    const certContent = `
<!DOCTYPE html>
<html>
<head>
  <title>Compliance Certificate - ${loan.borrower}</title>
  <style>
    body { font-family: 'Georgia', serif; padding: 60px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 3px double #1e40af; padding-bottom: 20px; margin-bottom: 30px; }
    .logo { font-size: 28px; color: #1e40af; font-weight: bold; }
    .title { font-size: 24px; color: #333; margin-top: 10px; }
    .certificate-id { font-size: 12px; color: #666; margin-top: 5px; }
    .content { line-height: 1.8; }
    .loan-details { background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e2e8f0; }
    .checks { margin: 20px 0; }
    .check-item { display: flex; align-items: center; gap: 10px; padding: 8px 0; }
    .check-pass { color: #16a34a; }
    .signature { margin-top: 40px; display: flex; justify-content: space-between; }
    .sig-block { text-align: center; }
    .sig-line { border-top: 1px solid #333; width: 200px; margin-top: 60px; padding-top: 5px; }
    .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #666; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    .seal { width: 80px; height: 80px; border: 3px solid #1e40af; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto; font-size: 10px; color: #1e40af; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">📊 LoanLedger</div>
    <div class="title">COMPLIANCE CERTIFICATE</div>
    <div class="certificate-id">Certificate ID: CERT-${Date.now()}</div>
  </div>
  
  <div class="content">
    <p>This is to certify that the following loan has successfully passed all required compliance checks and is cleared for trading on the LoanLedger platform.</p>
    
    <div class="loan-details">
      <div class="detail-row"><span>Loan ID:</span><strong>${loan.id}</strong></div>
      <div class="detail-row"><span>Borrower:</span><strong>${loan.borrower}</strong></div>
      <div class="detail-row"><span>Principal Amount:</span><strong>${new Intl.NumberFormat('en-US', { style: 'currency', currency: loan.currency }).format(loan.amount)}</strong></div>
      <div class="detail-row"><span>Risk Rating:</span><strong>${loan.riskRating}</strong></div>
      <div class="detail-row"><span>Default Probability:</span><strong>${loan.defaultProbability}%</strong></div>
      <div class="detail-row"><span>Originating Bank:</span><strong>${loan.originatingBank}</strong></div>
      <div class="detail-row"><span>Maturity Date:</span><strong>${new Date(loan.maturityDate).toLocaleDateString()}</strong></div>
    </div>

    <div class="checks">
      <h3>Compliance Checks Completed:</h3>
      <div class="check-item check-pass">✓ KYC Verification - Passed</div>
      <div class="check-item check-pass">✓ AML Screening - Passed</div>
      <div class="check-item check-pass">✓ Credit Limit Assessment - Passed</div>
      <div class="check-item check-pass">✓ Documentation Review - Passed</div>
      <div class="check-item check-pass">✓ Risk Threshold Check - Passed</div>
      ${loan.isGreen ? '<div class="check-item check-pass">✓ ESG Compliance - Verified Green Loan</div>' : ''}
    </div>

    <div class="signature">
      <div class="sig-block">
        <div class="sig-line">Compliance Officer</div>
      </div>
      <div class="seal">VERIFIED<br/>COMPLIANT</div>
      <div class="sig-block">
        <div class="sig-line">Date: ${new Date().toLocaleDateString()}</div>
      </div>
    </div>
  </div>

  <div class="footer">
    <p>This certificate is generated by LoanLedger's automated compliance system.</p>
    <p>All checks are recorded on the immutable audit trail. Certificate valid as of ${new Date().toLocaleString()}.</p>
    <p>For verification, contact compliance@loanledger.io</p>
  </div>
</body>
</html>`;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(certContent);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Risk & Compliance</h1>
        <p className="text-slate-500">Automated compliance monitoring and risk assessment</p>
      </div>

      {/* Problem Statement Banner */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 rounded-xl p-5 text-white">
        <h3 className="font-bold text-lg mb-2">Why This Matters</h3>
        <div className="grid grid-cols-3 gap-4 text-sm">
          <div className="bg-white/10 rounded-lg p-3">
            <p className="text-2xl font-bold">T+7</p>
            <p className="text-blue-200">Traditional loan settlement time</p>
          </div>
          <div className="bg-white/10 rounded-lg p-3">
            <p className="text-2xl font-bold">40+ hrs</p>
            <p className="text-blue-200">Manual compliance checks per trade</p>
          </div>
          <div className="bg-white/10 rounded-lg p-3">
            <p className="text-2xl font-bold">$2.5M</p>
            <p className="text-blue-200">Avg. annual compliance cost per bank</p>
          </div>
        </div>
        <p className="mt-3 text-blue-100 text-sm">LoanLedger automates these checks, reducing settlement time and compliance overhead by up to 80%.</p>
      </div>

      <div className="grid grid-cols-4 gap-4">
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center">
              <CheckCircle className="w-6 h-6 text-green-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-slate-900">{passedCount}</p>
              <p className="text-sm text-slate-500">Checks Passed</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-red-100 flex items-center justify-center">
              <XCircle className="w-6 h-6 text-red-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-slate-900">{failedCount}</p>
              <p className="text-sm text-slate-500">Checks Failed</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-amber-100 flex items-center justify-center">
              <Clock className="w-6 h-6 text-amber-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-slate-900">{pendingCount}</p>
              <p className="text-sm text-slate-500">Pending Review</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center">
              <Award className="w-6 h-6 text-blue-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-slate-900">{compliantLoans.length}</p>
              <p className="text-sm text-slate-500">Certified Loans</p>
            </div>
          </div>
        </div>
      </div>

      {/* Generate Certificate Section */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Award className="w-5 h-5 text-blue-600" />
            <h3 className="font-semibold text-slate-900">Generate Compliance Certificate</h3>
          </div>
        </div>
        <p className="text-sm text-slate-500 mb-4">Select a compliant loan to generate an official compliance certificate for regulators or investors.</p>
        <div className="grid grid-cols-2 gap-3">
          {compliantLoans.slice(0, 4).map((loan) => (
            <button
              key={loan.id}
              onClick={() => generateCertificate(loan)}
              className="flex items-center justify-between p-3 border border-slate-200 rounded-lg hover:bg-slate-50 hover:border-blue-300 transition-colors text-left"
            >
              <div>
                <p className="font-medium text-slate-900">{loan.borrower}</p>
                <p className="text-xs text-slate-500">{loan.id} • {loan.riskRating} Rating</p>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs px-2 py-1 bg-green-100 text-green-700 rounded">Compliant</span>
                <Download className="w-4 h-4 text-slate-400" />
              </div>
            </button>
          ))}
        </div>
      </div>

      {highRiskLoans.length > 0 && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-5">
          <div className="flex items-center gap-2 mb-3">
            <AlertTriangle className="w-5 h-5 text-red-600" />
            <h3 className="font-semibold text-red-900">High Risk Alerts</h3>
          </div>
          <div className="space-y-2">
            {highRiskLoans.map((loan) => (
              <div key={loan.id} className="flex items-center justify-between bg-white rounded-lg p-3">
                <div>
                  <p className="font-medium text-slate-900">{loan.borrower}</p>
                  <p className="text-sm text-slate-500">{loan.id} • {loan.loanType}</p>
                </div>
                <div className="text-right">
                  <p className="font-semibold text-red-600">{loan.defaultProbability}%</p>
                  <p className="text-xs text-slate-500">Default Probability</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="bg-white rounded-xl shadow-sm border border-slate-200">
        <div className="p-5 border-b border-slate-200">
          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-slate-600" />
            <h2 className="text-lg font-semibold text-slate-900">Compliance Checklist</h2>
          </div>
        </div>
        <div className="divide-y divide-slate-100">
          {checks.map((check) => {
            const config = statusConfig[check.status];
            const Icon = config.icon;
            const loan = loans.find(l => l.id === check.loanId);
            
            return (
              <div key={check.id} className="p-4 hover:bg-slate-50">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className={`w-8 h-8 rounded-full ${config.bg} flex items-center justify-center`}>
                      <Icon className={`w-4 h-4 ${config.color}`} />
                    </div>
                    <div>
                      <p className="font-medium text-slate-900">{check.checkType}</p>
                      <p className="text-sm text-slate-500">{loan?.borrower || check.loanId}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${config.bg} ${config.color}`}>
                      {check.status}
                    </span>
                    <p className="text-xs text-slate-500 mt-1">
                      {check.timestamp.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
                    </p>
                  </div>
                </div>
                <p className="text-sm text-slate-600 mt-2 ml-11">{check.details}</p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
